[Common]
Comment			= 이 실행파일은 RIS(인터) 랭킹, 로그삭제, DB Backup 기능을 합니다
ProcessTime		= 24
RankMonth		= 2

[DB]
Host			= localhost
User			= root
Passwd			= 123456
Database		= rakion
Port			= 3306

[DBUPDATE]
Host			= localhost
User			= root
Passwd			= 123456
Database		= rakion
Port			= 3306

[ABUSER]
CheckDay		= 1
CheckWinSum		= 200
CheckExpSum		= 6000
CheckGoldSum		= 12000

[DBBACKUP]
#원본파일 위치
SRC=F:\Servidor\Data\

#복사할 위치
DEST=E:\ServerMaster\RIS_RakionUpdate\DBBackup\


#복사할 파일
DBDATA=rakion
